In [1]:
import numpy as np
from sklearn.model_selection import ShuffleSplit

 


In [2]:
X = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [3, 4], [5, 6]])
y = np.array([1, 2, 1, 2, 1, 2])
rs = ShuffleSplit(n_splits=5, test_size=.25, random_state=0)
rs.get_n_splits(X)

5

In [13]:
ind=np.array([2,3])
X[ind]

array([[5, 6],
       [7, 8]])

In [14]:
import math

In [15]:
feature=31
X=[round(math.sqrt(feature)),feature//2]

In [16]:
print(X)

[6, 15]


In [5]:
rs.get_n_splits

<bound method BaseShuffleSplit.get_n_splits of ShuffleSplit(n_splits=5, random_state=0, test_size=0.25, train_size=None)>

In [11]:
for train_index, test_index in rs.split(X):
    print("TRAIN:", train_index, "TEST:", test_index, "type",type(train_index))
    print(X[train_index])

TRAIN: [1 3 0 4] TEST: [5 2] type <class 'numpy.ndarray'>
[[3 4]
 [7 8]
 [1 2]
 [3 4]]
TRAIN: [4 0 2 5] TEST: [1 3] type <class 'numpy.ndarray'>
[[3 4]
 [1 2]
 [5 6]
 [5 6]]
TRAIN: [1 2 4 0] TEST: [3 5] type <class 'numpy.ndarray'>
[[3 4]
 [5 6]
 [3 4]
 [1 2]]
TRAIN: [3 4 1 0] TEST: [5 2] type <class 'numpy.ndarray'>
[[7 8]
 [3 4]
 [3 4]
 [1 2]]
TRAIN: [3 5 1 0] TEST: [2 4] type <class 'numpy.ndarray'>
[[7 8]
 [5 6]
 [3 4]
 [1 2]]
