In [1]:
from keras.datasets import mnist

Using TensorFlow backend.


In [2]:
from keras import models
from keras import layers

In [3]:
from keras.datasets import mnist

In [28]:
import keras

In [153]:
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

In [5]:
train_images.shape

(60000, 28, 28)

In [152]:
train_labels

array([1, 0, 0, ..., 0, 1, 0], dtype=int64)

In [47]:
tl1=train_labels.reshape(1,-1)

In [48]:
tl1.shape

(1, 60000)

In [44]:
ti1=train_images.reshape(1,-1)

In [45]:
ti1.shape

(1, 47040000)

In [20]:
train_images = train_images.reshape((60000, 28 * 28))

In [46]:
train_images.shape

(60000, 784)

In [49]:
network = models.Sequential()
network.add(layers.Dense(512, activation='relu', input_shape=(784,)))
network.add(layers.Dense(10, activation='softmax'))

In [50]:
network.compile(optimizer='rmsprop',
loss='sparse_categorical_crossentropy',
metrics=['accuracy'])

In [39]:
keras.losses.categorical_crossentropy

<function keras.losses.categorical_crossentropy(y_true, y_pred)>

In [51]:
network.fit(train_images, train_labels, epochs=5, batch_size=128)

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where



Epoch 1/5





60000/60000 [==============================] - 6s 107us/step - loss: 9.3178 - acc: 0.4205
Epoch 2/5
60000/60000 [==============================] - 4s 62us/step - loss: 8.6240 - acc: 0.4643
Epoch 3/5
60000/60000 [==============================] - 4s 67us/step - loss: 8.5100 - acc: 0.4715
Epoch 4/5
60000/60000 [==============================] - 4s 70us/step - loss: 8.4105 - acc: 0.4778
Epoch 5/5
60000/60000 [==============================] - 4s 62us/step - loss: 8.3673 - acc: 0.4806


In [52]:
import numpy as np
x = np.random.random((64, 3, 32, 10))
y = np.random.random((32, 10))
z = np.maximum(x, y)

In [53]:
z.shape

(64, 3, 32, 10)

In [77]:
#x

In [56]:
#from keras.datasets import imdb
#np.load=np.load(allow_pickle=True)
#(train_data, train_labels), (test_data, test_labels) = imdb.load_data(num_words=10000)

In [57]:
np.__version__

'1.18.1'

In [58]:
np_load_old = np.load

# modify the default parameters of np.load
np.load = lambda *a,**k: np_load_old(*a, allow_pickle=True, **k)

# call load_data with allow_pickle implicitly set to true
(train_data, train_labels), (test_data, test_labels) = imdb.load_data(num_words=10000)

# restore np.load for future normal usage
np.load = np_load_old

In [157]:
train_labels[:30]

array([5, 0, 4, 1, 9, 2, 1, 3, 1, 4, 3, 5, 3, 6, 1, 7, 2, 8, 6, 9, 4, 0,
       9, 1, 1, 2, 4, 3, 2, 7], dtype=uint8)

In [158]:
y_train = np.asarray(train_labels).astype('float32')

In [160]:
type(train_labels)

numpy.ndarray

In [161]:
type(y_train)

numpy.ndarray

In [162]:
y_train

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [163]:
y_train

array([5., 0., 4., ..., 5., 6., 8.], dtype=float32)

In [64]:
word_index = imdb.get_word_index()

1646592/1641221 [==============================] - 2s 1us/step


In [72]:
for key,value in word_index.items():
    if value==0 or value == 1 or value==2 :
        print (key ,':',value)

the : 1
and : 2


In [93]:
reverse_word_index = dict(
[(value, key) for (key, value) in word_index.items()])
decoded_review = ' '.join(
[reverse_word_index.get(i - 3, '?') for i in train_data[5]])

In [94]:
decoded_review

"? begins better than it ends funny that the russian submarine crew ? all other actors it's like those scenes where documentary shots br br spoiler part the message ? was contrary to the whole story it just does not ? br br"

In [91]:
#len(train_data[0])
for i in range(10):
    print(i,len(train_data[i]))

0 218
1 189
2 141
3 550
4 147
5 43
6 123
7 562
8 233
9 130


In [96]:
type(train_data)

numpy.ndarray

In [85]:
train_data

array([list([1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65, 458, 4468, 66, 3941, 4, 173, 36, 256, 5, 25, 100, 43, 838, 112, 50, 670, 2, 9, 35, 480, 284, 5, 150, 4, 172, 112, 167, 2, 336, 385, 39, 4, 172, 4536, 1111, 17, 546, 38, 13, 447, 4, 192, 50, 16, 6, 147, 2025, 19, 14, 22, 4, 1920, 4613, 469, 4, 22, 71, 87, 12, 16, 43, 530, 38, 76, 15, 13, 1247, 4, 22, 17, 515, 17, 12, 16, 626, 18, 2, 5, 62, 386, 12, 8, 316, 8, 106, 5, 4, 2223, 5244, 16, 480, 66, 3785, 33, 4, 130, 12, 16, 38, 619, 5, 25, 124, 51, 36, 135, 48, 25, 1415, 33, 6, 22, 12, 215, 28, 77, 52, 5, 14, 407, 16, 82, 2, 8, 4, 107, 117, 5952, 15, 256, 4, 2, 7, 3766, 5, 723, 36, 71, 43, 530, 476, 26, 400, 317, 46, 7, 4, 2, 1029, 13, 104, 88, 4, 381, 15, 297, 98, 32, 2071, 56, 26, 141, 6, 194, 7486, 18, 4, 226, 22, 21, 134, 476, 26, 480, 5, 144, 30, 5535, 18, 51, 36, 28, 224, 92, 25, 104, 4, 226, 65, 16, 38, 1334, 88, 12, 16, 283, 5, 16, 4472, 113, 103, 32, 15, 16, 5345, 19, 178, 32]),
       list([1, 194, 1153, 194, 8255, 78, 228,

In [112]:
n_test_array=np.array([list([1,2,3,4]),list([3,4,5,6,7])])

In [116]:
type(n_test_array)

numpy.ndarray

In [117]:
n_test_array

array([list([1, 2, 3, 4]), list([3, 4, 5, 6, 7])], dtype=object)

In [143]:
nnn=np.array([1,2,3,4,5,6])

In [146]:
nnn1=nnn.reshape(3,2)

In [150]:
nnn1[1,[0,1]]=[7,8]

In [151]:
nnn1[1,1]

8

In [123]:
arar=np.zeros(shape=(len(nnn),10))

In [138]:
nnn

array([list([1, 2, 3, 4]), list([3, 4, 5, 6, 7])], dtype=object)

In [106]:
train_data.shape

(25000,)

In [97]:
list([1,2,3,4])

[1, 2, 3, 4]

In [110]:
p=np.array([1, 2, 3])

In [111]:
type(p)

numpy.ndarray

In [60]:
max([max(sequence) for sequence in train_data])

9999

In [62]:
from keras import models
from keras import layers
model = models.Sequential()
model.add(layers.Dense(16, activation='relu', input_shape=(10000,)))
model.add(layers.Dense(16, activation='relu'))
model.add(layers.Dense(1, activation='sigmoid'))

In [63]:
model.compile(optimizer='rmsprop',loss='binary_crossentropy',metrics=['accuracy'])
#model.compile(optimizer=optimizers.RMSprop(lr=0.001),loss='binary_crossentropy',metrics=['accuracy'])
#model.compile(optimizer=optimizers.RMSprop(lr=0.001),loss=losses.binary_crossentropy,metrics=[metrics.binary_accuracy])

In [ ]:
len()