In [1]:
from keras.datasets import mnist

Using TensorFlow backend.


In [2]:
from keras import models
from keras import layers

In [3]:
from keras.datasets import mnist

In [4]:
import keras

In [5]:
#np.load = np_load_old

In [6]:
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

In [7]:
train_images.shape

(60000, 28, 28)

In [8]:
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [9]:
tl1=train_labels.reshape(1,-1)

In [10]:
tl1.shape

(1, 60000)

In [11]:
ti1=train_images.reshape(1,-1)

In [12]:
ti1.shape

(1, 47040000)

In [13]:
train_images = train_images.reshape((60000, 28 * 28))

In [14]:
train_images.shape

(60000, 784)

In [15]:
network = models.Sequential()
network.add(layers.Dense(512, activation='relu', input_shape=(784,)))
network.add(layers.Dense(10, activation='softmax'))

In [16]:
network.compile(optimizer='rmsprop',
loss='sparse_categorical_crossentropy',
metrics=['accuracy'])

In [17]:
keras.losses.categorical_crossentropy

<function keras.losses.categorical_crossentropy(y_true, y_pred)>

In [18]:
network.fit(train_images, train_labels, epochs=5, batch_size=128)

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where



Epoch 1/5





60000/60000 [==============================] - 5s 77us/step - loss: 13.0800 - acc: 0.1880
Epoch 2/5
60000/60000 [==============================] - 4s 70us/step - loss: 10.5108 - acc: 0.3470
Epoch 3/5
60000/60000 [==============================] - 4s 66us/step - loss: 10.2868 - acc: 0.3614
Epoch 4/5
60000/60000 [==============================] - 4s 69us/step - loss: 10.2595 - acc: 0.3631
Epoch 5/5
60000/60000 [==============================] - 4s 72us/step - loss: 10.2250 - acc: 0.3653


In [19]:
import numpy as np
x = np.random.random((64, 3, 32, 10))
y = np.random.random((32, 10))
z = np.maximum(x, y)

In [20]:
z.shape

(64, 3, 32, 10)

In [21]:
#x

In [22]:
#from keras.datasets import imdb
#np.load=np.load(allow_pickle=True)
#(train_data, train_labels), (test_data, test_labels) = imdb.load_data(num_words=10000)

In [23]:
np.__version__

'1.18.1'

In [24]:
from keras.datasets import imdb
np_load_old = np.load

# modify the default parameters of np.load
np.load = lambda *a,**k: np_load_old(*a, allow_pickle=True, **k)

# call load_data with allow_pickle implicitly set to true
(train_data, train_labels), (test_data, test_labels) = imdb.load_data(num_words=10000)

# restore np.load for future normal usage
np.load = np_load_old

In [25]:
train_labels[:30]

array([1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       1, 0, 1, 1, 0, 0, 1, 0], dtype=int64)

In [26]:
y_train = np.asarray(train_labels).astype('float32')

In [27]:
type(train_labels)

numpy.ndarray

In [28]:
type(y_train)

numpy.ndarray

In [29]:
y_train

array([1., 0., 0., ..., 0., 1., 0.], dtype=float32)

In [30]:
y_train

array([1., 0., 0., ..., 0., 1., 0.], dtype=float32)

In [31]:
word_index = imdb.get_word_index()

In [32]:
for key,value in word_index.items():
    if value==0 or value == 1 or value==2 :
        print (key ,':',value)

the : 1
and : 2


In [33]:
reverse_word_index = dict(
[(value, key) for (key, value) in word_index.items()])
decoded_review = ' '.join(
[reverse_word_index.get(i - 3, '?') for i in train_data[5]])

In [34]:
decoded_review

"? begins better than it ends funny that the russian submarine crew ? all other actors it's like those scenes where documentary shots br br spoiler part the message ? was contrary to the whole story it just does not ? br br"

In [35]:
#len(train_data[0])
for i in range(10):
    print(i,len(train_data[i]))

0 218
1 189
2 141
3 550
4 147
5 43
6 123
7 562
8 233
9 130


In [36]:
type(train_data)

numpy.ndarray

In [37]:
train_data

array([list([1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65, 458, 4468, 66, 3941, 4, 173, 36, 256, 5, 25, 100, 43, 838, 112, 50, 670, 2, 9, 35, 480, 284, 5, 150, 4, 172, 112, 167, 2, 336, 385, 39, 4, 172, 4536, 1111, 17, 546, 38, 13, 447, 4, 192, 50, 16, 6, 147, 2025, 19, 14, 22, 4, 1920, 4613, 469, 4, 22, 71, 87, 12, 16, 43, 530, 38, 76, 15, 13, 1247, 4, 22, 17, 515, 17, 12, 16, 626, 18, 2, 5, 62, 386, 12, 8, 316, 8, 106, 5, 4, 2223, 5244, 16, 480, 66, 3785, 33, 4, 130, 12, 16, 38, 619, 5, 25, 124, 51, 36, 135, 48, 25, 1415, 33, 6, 22, 12, 215, 28, 77, 52, 5, 14, 407, 16, 82, 2, 8, 4, 107, 117, 5952, 15, 256, 4, 2, 7, 3766, 5, 723, 36, 71, 43, 530, 476, 26, 400, 317, 46, 7, 4, 2, 1029, 13, 104, 88, 4, 381, 15, 297, 98, 32, 2071, 56, 26, 141, 6, 194, 7486, 18, 4, 226, 22, 21, 134, 476, 26, 480, 5, 144, 30, 5535, 18, 51, 36, 28, 224, 92, 25, 104, 4, 226, 65, 16, 38, 1334, 88, 12, 16, 283, 5, 16, 4472, 113, 103, 32, 15, 16, 5345, 19, 178, 32]),
       list([1, 194, 1153, 194, 8255, 78, 228,

In [38]:
n_test_array=np.array([list([1,2,3,4]),list([3,4,5,6,7])])

In [39]:
type(n_test_array)

numpy.ndarray

In [40]:
n_test_array

array([list([1, 2, 3, 4]), list([3, 4, 5, 6, 7])], dtype=object)

In [41]:
nnn=np.array([1,2,3,4,5,6])

In [42]:
nnn1=nnn.reshape(3,2)

In [43]:
nnn1


array([[1, 2],
       [3, 4],
       [5, 6]])

In [44]:
nnn1.shape 

(3, 2)

In [45]:
nnn1[1,1]

4

In [46]:
arar=np.zeros(shape=(len(nnn),10))

In [47]:
nnn

array([1, 2, 3, 4, 5, 6])

In [48]:
train_data.shape

(25000,)

In [49]:
list([1,2,3,4])

[1, 2, 3, 4]

In [50]:
p=np.array([1, 2, 3])

In [51]:
type(p)

numpy.ndarray

In [52]:
max([max(sequence) for sequence in train_data])

9999

In [53]:
from keras import models
from keras import layers
model = models.Sequential()
model.add(layers.Dense(16, activation='relu', input_shape=(10000,)))
model.add(layers.Dense(16, activation='relu'))
model.add(layers.Dense(1, activation='sigmoid'))

In [54]:
model.compile(optimizer='rmsprop',loss='binary_crossentropy',metrics=['accuracy'])
#model.compile(optimizer=optimizers.RMSprop(lr=0.001),loss='binary_crossentropy',metrics=['accuracy'])
#model.compile(optimizer=optimizers.RMSprop(lr=0.001),loss=losses.binary_crossentropy,metrics=[metrics.binary_accuracy])

In [59]:
type(train_labels)

numpy.ndarray

In [60]:
y_test = np.asarray(test_labels).astype('float32')

In [61]:
type(y_test)

numpy.ndarray

[1,
 17,
 6,
 194,
 337,
 7,
 4,
 204,
 22,
 45,
 254,
 8,
 106,
 14,
 123,
 4,
 2,
 270,
 2,
 5,
 2,
 2,
 732,
 2098,
 101,
 405,
 39,
 14,
 1034,
 4,
 1310,
 9,
 115,
 50,
 305,
 12,
 47,
 4,
 168,
 5,
 235,
 7,
 38,
 111,
 699,
 102,
 7,
 4,
 4039,
 9245,
 9,
 24,
 6,
 78,
 1099,
 17,
 2345,
 2,
 21,
 27,
 9685,
 6139,
 5,
 2,
 1603,
 92,
 1183,
 4,
 1310,
 7,
 4,
 204,
 42,
 97,
 90,
 35,
 221,
 109,
 29,
 127,
 27,
 118,
 8,
 97,
 12,
 157,
 21,
 6789,
 2,
 9,
 6,
 66,
 78,
 1099,
 4,
 631,
 1191,
 5,
 2642,
 272,
 191,
 1070,
 6,
 7585,
 8,
 2197,
 2,
 2,
 544,
 5,
 383,
 1271,
 848,
 1468,
 2,
 497,
 2,
 8,
 1597,
 8778,
 2,
 21,
 60,
 27,
 239,
 9,
 43,
 8368,
 209,
 405,
 10,
 10,
 12,
 764,
 40,
 4,
 248,
 20,
 12,
 16,
 5,
 174,
 1791,
 72,
 7,
 51,
 6,
 1739,
 22,
 4,
 204,
 131,
 9]

In [87]:
def transform(data):
    temp=np.zeros((len(data),10000))
    for i,data_ind in enumerate(data):
        temp[i,data_ind]=1
    return temp

In [86]:
len(train_data)

25000

In [88]:
train_data1=transform(train_data)

In [89]:
test_data1=transform(test_data)

In [63]:
#train_data, train_labels), (test_data, test_labels)

In [90]:
X_train=train_data1[10000:]
y_train=train_labels[10000:]
X_test=test_data1.copy()
y_test=test_labels.copy()
X_val=X_train[:10000]
y_val=y_train[:10000]


In [91]:
X_train.shape

(15000, 10000)

In [92]:
history=model.fit(X_train,y_train,epochs=20,batch_size=512,validation_data=(X_val,y_val))

Train on 15000 samples, validate on 10000 samples
Epoch 1/20
15000/15000 [==============================] - 17s 1ms/step - loss: 0.5085 - acc: 0.7815 - val_loss: 0.3334 - val_acc: 0.9043
Epoch 2/20
15000/15000 [==============================] - 3s 173us/step - loss: 0.3005 - acc: 0.9045 - val_loss: 0.2224 - val_acc: 0.9407
Epoch 3/20
15000/15000 [==============================] - 2s 163us/step - loss: 0.2180 - acc: 0.9286 - val_loss: 0.1929 - val_acc: 0.9327
Epoch 4/20
15000/15000 [==============================] - 2s 144us/step - loss: 0.1751 - acc: 0.9436 - val_loss: 0.1378 - val_acc: 0.9617
Epoch 5/20
15000/15000 [==============================] - 2s 154us/step - loss: 0.1428 - acc: 0.9541 - val_loss: 0.1068 - val_acc: 0.9714
Epoch 6/20
15000/15000 [==============================] - 2s 147us/step - loss: 0.1151 - acc: 0.9651 - val_loss: 0.0965 - val_acc: 0.9707
Epoch 7/20
15000/15000 [==============================] - 2s 153us/step - loss: 0.0980 - acc: 0.9707 - val_loss: 0.0692 - v

In [93]:
history_dict=history.history

In [106]:
history_dict.keys()

dict_keys(['val_loss', 'val_acc', 'loss', 'acc'])

In [107]:
#history_dict['val_acc']

In [100]:
import matplotlib.pyplot as plt
%matplotlib inline

In [109]:
plt.plot(history_dict['val_loss'],'bo',label="val loss")
plt.plot(history_dict['loss'],'b',label='loss')
plt.legend()

In [111]:
result=model.evaluate(X_test,y_test)

25000/25000 [==============================] - 3s 136us/step


In [113]:
result

[0.7748266851973533, 0.85112]

In [114]:
model.metrics_names

['loss', 'acc']

In [ ]:
y_train = np.array(train_labels)
y_test = np.array(test_labels)