In [1]:
import tensorflow as tf
import numpy as np

In [4]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


In [10]:
indices = [0, 1, 2,1,1,1]
depth = 4
one_hot_enc=tf.one_hot(indices, depth) 

In [11]:
with tf.Session() as sess:
    print(sess.run(one_hot_enc))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]]
